name: Spellcheck
on:
  push:
    branches: ['main']
jobs:
  Spelling:
    runs-on: ubuntu-latest
    container:
      image: "rocker/tidyverse:4.4.1"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          if (!require("spelling")) install.packages("spelling")
          if (!require("readr")) install.packages("readr")
        shell: Rscript {0}

      - name: Remove links from .qmd files
        run: |
          find . -type f -name "*.qmd" -print0 | while IFS= read -r -d '' file; do
            sed -i -E 's/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/\1/g' "$file"
            sed -i -E 's#https?://[a-zA-Z0-9./?=_&#-]+##g' "$file"
          done
        shell: bash

      - name: Check spelling
        run: |
          library(spelling)
          library(readr)

          wordlist_path <- "WORDLIST"
          ignore_words <- if (file.exists(wordlist_path)) read_lines(wordlist_path) else character(0)

          qmd_files <- list.files(pattern = "\\.qmd$", recursive = TRUE)
          words <- spell_check_files(qmd_files, ignore = ignore_words)

          if (nrow(words) > 0) {
            print(words)
            stop("Spelling errors found. Add valid terms to WORDLIST.")
          }
        shell: Rscript {0}
